name: Secrets Check
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  secrets-scan:
    uses: IDme/workflow-library/.github/workflows/code-checks-secrets.yml@master
    secrets: inherit
