name: Secure Pipeline | AST

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft
  schedule:
    - cron: '0 8 * * *' # 3am EST (UTC-5)

jobs:
  execute:
    uses: IDme/workflow-library/.github/workflows/secure-pipeline-ast.yml@master
    secrets: inherit
